# Generated by Django 5.0.3 on 2024-04-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='editorial',
            field=models.CharField(default='xyz', max_length=100),
        ),
        migrations.AddField(
            model_name='topic',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
    ]
